### ISSUE TITLE
Adapt CCL to new decisions by court?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#31]
See https://www.fr.de/panorama/bleibt-vollstaendig-eine-dosis-johnson-johnson-reicht-jetzt-doch-gericht-entscheidet-impfstatus-zr-91359752.html:

- One vaccination with J&J is full vaccination protection
- The recovery certificate is valid 6 months

**Comment by DerVogel2020** [comment]
Does this apply only to Hamburg or to all states?

**Comment by Ein-Tim** [comment]
@DerVogel2020 

This is the question, also whether this only applies to this one case or to all cases.

**Comment by mlenkeit** [comment]
@Ein-Tim thanks for bringing this up here! We are aware of these court rulings, however, here's no clear requirement yet to reflect this in CCL. We'll keep this issue open until there's a final decision.

**Comment by Doxylamin** [comment]
In addition to the recent court ruling on the Janssen vaccine, it is equally misleading that both CovPass (version 1.18.0, Android 11), and CovPassCheck (version 1.18.0, Android 11) show a complete immunization status, while the CWA app is the only app that does not.

I would therefore generally roll back the change to the Janssen vaccination status and wait for a legally valid ruling from the relevant authority, rather than implementing the recommendation of an institute as "legally binding and valid", as decided by the berlin court (Related press release: https://www.berlin.de/gerichte/verwaltungsgericht/presse/pressemitteilungen/2022/pressemitteilung.1178438.php)

**Comment by Ein-Tim** [comment]
@Doxylamin 

Thanks for the info.

Does CovPassCheck shows J&J vaccine valid in both "Prüfsituationen" (Einreise nach Deutschland & Innerhalb Deutschlands)?

**Comment by Doxylamin** [comment]
> Does CovPassCheck show a J&J vaccine valid in both "Prüfsituationen" (Einreise nach Deutschland & Innerhalb Deutschlands)?

Yes. I've now validated the following scenarios, all showing valid immunization status within CovPassCheck:

|     | Entry to Germany | Within Germany |
|-----|------------------|----------------|
| 3G  | Valid            | Valid          |
| 2G+ | Valid            | Valid          |

2G+ was tested with a single dose Janssen vaccination plus a negative rapid test result.

**Comment by Doxylamin** [comment]
I would suggest adapting CWA to the current ruleset that CovPass(Check) is using, simply due to the press release (translated w/ Deepl):

> This is because, according to the ordinance authorization in the Infection Protection Act, the federal government itself has to decide on the immunization status (also as a result of protective vaccinations). The transfer of this decision to the Paul Ehrlich Institute exceeds the limits of the statutory authorization.

**Comment by Ein-Tim** [comment]
@mlenkeit Two months have passed, has a decision. been made?

**Comment by MikeMcC399** [comment]
Also the rules have to adapt to [Infektionsschutzgesetz - IfSG](https://www.gesetze-im-internet.de/ifsg/) - "Infektionsschutzgesetz vom 20. Juli 2000 (BGBl. I S. 1045), das zuletzt durch Artikel 4 des Gesetzes vom 18. März 2022 (BGBl. I S. 473) geändert worden ist".

Some of the court rulings will no longer apply because the law has been changed in the new edition of [Infektionsschutzgesetz - IfSG](https://www.gesetze-im-internet.de/ifsg/) from March 18, 2022.

It's also further complicated by the differing regulations in each federal state, where most of them have dropped any definition of 2G/2G+/3G. (See also discussion in https://github.com/corona-warn-app/cwa-app-ccl/issues/35#issuecomment-1106051331.)

**Comment by Ein-Tim** [comment]
@MikeMcC399 Agreed, I guess the decision which the court made I posted a link to in the OP is probably not relevant anymore, however, @mlenkeit said he will come back to us once there was a decision made, so either no decision has been made or there was a decision which can be shared here.

**Comment by mlenkeit** [comment]
@Ein-Tim the decision for now is to leave CCL unchanged.

**Comment by Ein-Tim** [comment]
Thanks @mlenkeit!
