### ISSUE TITLE
Legal basis for showing 2G+ for 90 days when recovered

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#35]
Please share the legal basis for showing 2G+ for 90 days with a recovery certificate. I did not find it.

**Comment by Ein-Tim** [comment]
@mlenkeit Can we expect any response here?

cc @dsarkar

**Comment by Ein-Tim** [comment]
@dsarkar Will issues in the https://github.com/corona-warn-app/cwa-app-ccl repo be mirrored to JIRA?

**Comment by dsarkar** [comment]
@Ein-Tim will clarify this.... stand by...

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Does 2G+ still have a legal meaning?

For instance: https://www.br.de/radio/bayern1/2g-plus-100.html "Kein 2G plus mehr in Bayern
Zum 3. April 2022 gilt 2G plus nicht mehr in Bayern. Was 2G plus überhaupt bedeutet und wen es im Ernstfall betrifft."

**Comment by Ein-Tim** [comment]
@MikeMcC399 All this has to be clarified from the team / the stakeholders, because their app is currently showing 2G+ for 90 days when one is recovered. I would expect that it only shows 2G, without an additional test certificate registered in the app. 

What 2G+ actually means as legal definition is complicated, due to the fact that it is not used anymore, I think.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

It seems to correspond with the FAQ definition https://www.coronawarn.app/en/faq/results/#admission_policy_2gplus "What does the 2G+ status proof mean in concrete terms?"

![image](https://user-images.githubusercontent.com/66998419/164445225-3551f08d-803c-43d5-be24-151b8cfeda6e.png)

which also links to https://www.bundesregierung.de/breg-de/themen/coronavirus/corona-bundeslaender-1745198 where it says:

![image](https://user-images.githubusercontent.com/66998419/164445428-3be8623f-e345-45f4-902a-931ae73328bd.png)

So there is probably only a historical legal basis as an answer to your question.

I did not attempt to look through the regulations for the individual federal states.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I agree, it is currently hard to examine & also not very relevant, but I opened this issue nearly two months ago, so the team had plenty of time to respond on it and I will wait until I get an answer here. Sorry, but not answering to issues doesn't make them go away in my opinion.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I think there is a new topic now, which should go into cwa-documentation:

- Is there any legal definition for 2G, 2G+ and 3G at this time?
- If there is no longer a legal definition for these terms, should the app still display them?

Maybe somebody from the team could give a hint about the plans for this?

**Comment by Ein-Tim** [comment]
@MikeMcC399 I agree, if such an issue is opened, I would close this one.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I found that Hamburg is continuing with 2G+ until the end of April 2022.

https://www.hamburg.de/coronavirus/16038886/2022-03-31-sozialbehoerde-corona-eindaemmungsverordnung/

"Der Zutritt zu Clubs und Diskotheken ist im Rahmen des 2Gplus-Zugangsmodells möglich, das heißt, nur mit einem Nachweis über drei Impfungen bzw. zwei Impfungen und einer Genesung. Bei zwei Impfungen, einer Impfung und Genesung oder einer Genesung, die höchstens 90 Tage zurückliegt, muss zusätzlich ein negativer Schnell- oder PCR-Test vorgelegt werden."

I don't know if this definition is the same everywhere, that's to say in the federal states which are continuing with any sort of 2G/2G+/3G rule.

I guess if you want to check the programmed rules against the legal rules you would need to concentrate on a specific personal example case in a specific federal state otherwise you get lost in the complexity.

**Comment by Ein-Tim** [comment]
@MikeMcC399 That's also how Bavaria handled it: https://www.stmgp.bayern.de/presse/gesundheitsministerium-erlaeutert-2g-und-2g-plus-regeln-keine-uebergangsregeln-fuer/

And that's also how most other federal states had their rules.

So, again: Why is 2G+ shown for 90 days, although this seems to be off with the legal basis in most federal states.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

https://www.dehoga-corona.de/auflagen-praxishilfen/verordnungen-der-bundeslaender/ seems to be a good source of overviews. As they say: "Die für Hotellerie und Gastronomie, Veranstaltungen, Clubs und Diskotheken und viele andere Bereiche geltenden Einschränkungen werden von den einzelnen Bundesländern geregelt. Diese Regelungen unterscheiden sich erheblich."

So, if CWA tries to have one set of rules for all federal states, that will not work.

https://www.dehoga-corona.de/fileadmin/user_upload/UEbersicht_Bundeslaender_Hotspotregelungen_in_HH_und_MV_Stand_2022_04_20.pdf gives an overview of where 2G/2G+/3G is still in use.

The definitions of 2G+ for HH and MV are different from one another.

**Comment by Ein-Tim** [comment]
Thanks for the list @MikeMcC399.

In HH 2G+ is not reached with only being recovered, in MV it is as CWA implemented it.

I'll close this issue now, it doesn't make sense to push this percise one forward. I'll open a more general issue later.

Still I think it's sad that issues can be left unanswered for so long.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I followed up in https://github.com/corona-warn-app/cwa-app-ccl/issues/74.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This could be a topic for a wish-list item to have CWA show status according to the federal state. 

Currently even the specialized CovPassCheck App does not adapt to individual state rules. For checking within Germany there are no options for 3G in the CovPassCheck App. For 2G+ there is the option "No test is needed when a booster vaccination is given". This doesn't cover all cases though.

Since most states have stopped using 2G/2G+/3G there is probably little incentive to enhance the CWA app in this area though, so I don't intend to submit a request for this. 

The best case for the future would be for all states to stop using 2G/2G+/3G. If it needs to be introduced again after the summer, then the best case would be for Germany-wide definitions to be made (no local exceptions). The worst case would be once again each state making its own definitions, then introducing them at different times and making continual changes.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> This could be a topic for a wish-list item to have CWA show status according to the federal state.

The app is actually prepared for this, however, the federal sates did never report their rules to a central authority so the feature was never activated. See https://github.com/corona-warn-app/cwa-app-ios/pull/4272#issuecomment-1056782995

Reg. the rest of your comment: 💯% agreed on this!

**Comment by MikeMcC399** [comment]
> @Ein-Tim 
> > This could be a topic for a wish-list item to have CWA show status according to the federal state.
> 
> The app is actually prepared for this, however, the federal sates did never report their rules to a central authority so the feature was never activated. See [corona-warn-app/cwa-app-ios#4272 (comment)](https://github.com/corona-warn-app/cwa-app-ios/pull/4272#issuecomment-1056782995)

Was the CWA Android app also prepared? I could not find anything for Android.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Was the CWA Android app also prepared? I could not find anything for Android.

Sorry, I don't know. As you know, I follow iOS more closely than Android!
